### ISSUE TITLE
Advancements are being randomly reset.

### ISSUE THREAD

**Issue by ConfuseN** [Proximyst/Rainforest#3]
**Describe the bug**
Advancements are being randomly reset.

**To Reproduce**
Hard to find steps to reproduce, but this is what happens in console before
a player is reset:
https://pastebin.com/Me8HabXa

**Plugins**
https://i.imgur.com/j8e50O4.png

**Misc**
For reference: https://github.com/YatopiaMC/Yatopia/issues/126

**Comment by MrIvanPlays** [comment]
@Proximyst still can reproduce, although steps are still not clear
YatopiaMC/Yatopia#126 a guy mentioned that he reproduced it again.

**Comment by Proximyst** [comment]
@MrIvanPlays Then I don't really care; logging in from other locations is very sketchy as a whole.

**Comment by MrIvanPlays** [comment]
alright

**Comment by epserv** [comment]
What can I do to prevent this? Or "Proximyst added a commit that referenced this issue 3 days ago" fixes this?
